FROM node:20.12

ARG AUTH_SECRET=${AUTH_SECRET}
ENV AUTH_SECRET=${AUTH_SECRET}
ARG SMTP_EMAIL_SERVER=${SMTP_EMAIL_SERVER}
ENV SMTP_EMAIL_SERVER=${SMTP_EMAIL_SERVER}
ARG SMTP_EMAIL_FROM=${SMTP_EMAIL_FROM}
ENV SMTP_EMAIL_FROM=${SMTP_EMAIL_FROM}
ARG NEXT_PUBLIC_SENTRY_DSN=${NEXT_PUBLIC_SENTRY_DSN}
ENV NEXT_PUBLIC_SENTRY_DSN=${NEXT_PUBLIC_SENTRY_DSN}
ARG DATABASE_URL=${DATABASE_URL}
ENV DATABASE_URL=${DATABASE_URL}


WORKDIR /app
COPY package.json pnpm-lock.yaml ./
RUN npm install -g pnpm && \
    pnpm install --ignore-scripts
COPY . .
RUN pnpm prisma generate
RUN pnpm run build
EXPOSE 3000
RUN chmod +x entrypoint.sh
ENTRYPOINT [ "/app/entrypoint.sh" ]