import '@/styles/globals.css'
import { type Metadata } from 'next'

export const metadata: Metadata = {
  title: 'PEpe Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
}

export default function AuthLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <div className="mx-auto flex h-full max-w-4xl items-center justify-center sm:max-w-[360px]">
      {children}
    </div>
  )
}
