name: NextJS build validation

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  validation:
    name: NextJS build validation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Enable corepack
        run: corepack enable

      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Copy ENV files
        run: cp .env.test .env

      - name: Build NextJS app
        run: pnpm run build
